name: Build APK
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip project
        run: unzip -q gkart-android-app.zip
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'
      - name: Build debug APK
        working-directory: gkart-app
        run: gradle assembleDebug --stacktrace --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: gkart-debug-apk
          path: gkart-app/app/build/outputs/apk/debug/*.apk
